AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure for Cloud Resume - S3 bucket for static website hosting.

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket for resume website
    Default: resume

Resources:
  ResumeBucket:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  ResumeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResumeBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${ResumeBucket.Arn}/*'

Outputs:
  BucketName:
    Value: !Ref ResumeBucket
    Description: Name of the S3 bucket
  BucketArn:
    Value: !GetAtt ResumeBucket.Arn
    Description: ARN of the S3 bucket
  WebsiteURL:
    Value: !GetAtt ResumeBucket.WebsiteURL
    Description: URL of the S3 website endpoint